vulns.append(newCommandObject('cat "/home/sackboy/Desktop/Forensics Question 1"', 'Play! Create! Share! Huzzah!', True, 8, 'Forensics question 1 solved'))
vulns.append(newCommandObject('cat "/home/sackboy/Desktop/Forensics Question 2"', '/etc/passwd', True, 8, 'Forensics question 2 solved'))
vulns.append(newCommandObject('cat "/home/sackboy/Desktop/Forensics Question 3"', '192.168.0.15', True, 8, 'Forensics question 3 solved'))
vulns.append(newUserObject('newton', False, None, None, 2, 'Removed hidden root newton'))
vulns.append(newUserObject('sackbot', False, None, None, 1, 'Removed unauthorized user sackbot'))
vulns.append(newUserObject('sackgirl', True, True, '!', 1, 'Set a password for sackgirl'))
vulns.append(newUserObject('negativatron', False, None, None, 2, 'Removed unauthorized hidden user negativatron'))
vulns.append(newCommandObject('sudo -l -U larrydavinci | grep "not allowed"', 'not allowed', True, 2, 'Larry Davinci is not an admin'))
vulns.append(newCommandObject('cat /etc/group | grep sudo | grep narrator', 'narrator', True, 1,  'Narrator is an admin'))
vulns.append(newCommandObject('cat /etc/sudoers | grep -c auth', '1', True, 1, 'Removed authentication bypass'))
vulns.append(newCommandObject('cat /etc/sudoers | grep -c auth', '0', True, 1, 'Removed authentication bypass'))
vulns.append(newCommandObject('cat /etc/sudoers.d/README | grep auth', "authenticate", False, 1, 'Removed authentication bypass'))
vulns.append(newCommandObject('ls /media/album | grep [.]mp3', 'mp3', False, 1, 'Removed unauthorized MP3 files'))
vulns.append(newCommandObject('ls /mnt/moon | grep passwords', 'passwords', False, 2, 'Removed plaintext passsword file'))
vulns.append(newCommandObject('cat /etc/samba/smb.conf | grep -i printers', 'printers', False, 2, 'Removed printers share'))
vulns.append(newCommandObject('cat /etc/samba/smb.conf | grep -i negativatron', 'negativatron', False, 1, 'Removed negativatron share'))
vulns.append(newCommandObject('cat /etc/crontab | grep "nc "', 'nc', False, 1, 'Removed backdoor in /etc/crontab'))
vulns.append(newCommandObject('cat /var/spool/cron/crontabs/root | grep "nc "', 'nc', False, 2, 'Removed backdoor in roots crontab'))
vulns.append(newCommandObject('ls -l /mnt | grep moon | grep drw-r-----', "drw-r-----", True, 2, 'Secure file permissions set for /mnt/moon'))
vulns.append(newCommandObject('ufw status', 'Status: active', True, 1, 'Firewall is enabled'))
vulns.append(newUserObject('root', True, True, '!', 1, 'Changed insecure root password'))
vulns.append(newConfigObject('/etc/login.defs', 'PASS_MAX_DAYS', '15', '\t', 2, 'A default maxiumum password age is set'))
vulns.append(newConfigObject('/etc/login.defs', 'PASS_MIN_DAYS', '7', '\t', 2, 'A default minimum password age is set'))
vulns.append(newCommandObject('ls /bin', 'ex1t', False, 5, 'Removed bad executable ex1t'))
vulns.append(newCommandObject('cat /etc/pam.d/common-password','minlen=', True, 2, 'A minimum length has been set for passwords'))
vulns.append(newCommandObject('cat /etc/rc.local', 'ex1t', False, 2, 'Removed startup backdoor'))
vulns.append(newCommandObject('ufw show added', 'deny 21', False, 4, 'Firewall allows port 21'))
vulns.append(newCommandObject('cat /etc/ssh/sshd_config | grep X11Forwarding', 'no', True, 2, 'Disabled X11 Forwarding'))
vulns.append(newCommandObject('cat /etc/ssh/sshd_config | grep PermitRootLogin', 'no', True, 2, 'Disabled root login via ssh'))
vulns.append(newCommandObject('cat /etc/ssh/sshd_config | grep Protocol', '2', True, 2, 'SSH Protocol set to 2'))
vulns.append(newCommandObject('ls /etc/cron.d', 'runcheck', False, 2, 'Removed backdoor in crontab'))
vulns.append(newCommandObject('ls -l /etc | grep -v gshadow | grep -v shadow- | grep shadow', '-rw-r-----', True, 2, 'Secure file permissions set for shadow file'))
vulns.append(newCommandObject('ls /var', 'timemachine', False, 3, 'Removed the timemachine'))
vulns.append(newCommandObject('cat /etc/samba/smb.conf | grep -A 8 "\[moon\]" | grep "guest ok"', 'no', True, 2, 'moon share does not allow guests'))
vulns.append(newCommandObject('cat /etc/samba/smb.conf | grep -A 8 "\[moon\]" | grep "create mask"', '0640', True, 2, 'moon share create mask hardened'))
vulns.append(newCommandObject('cat /etc/vsftpd.conf | grep -v "#"', 'anonymous_enable=NO', True, 1, 'VSFTPD no longer allows anonymous access'))
vulns.append(newCommandObject('cat /etc/vsftpd.conf | grep -v "#"', 'secure_chroot_dir=/var/chroot', True, 1, 'VSFTPD chroot is properly configured'))
vulns.append(newCommandObject('cat /etc/sysctl.conf | grep -v "#"', 'net.ipv4.icmp_echo_ignore_broadcasts = 1', True, 2, 'Ignore IPv4 ICMP echo broadcasts'))
vulns.append(newCommandObject('cat /etc/apt/apt.conf.d/20auto-upgrades | grep Update-Package-Lists', '"1"', True, 2, 'Automatically checks for updates'))
vulns.append(newCommandObject('apt list --installed | grep ophcrack/', 'installed', False, 2, 'Prohibited software ophcrack removed'))
vulns.append(newCommandObject('apt list --installed | grep wireshark/', 'installed', False, 2, 'Prohibited software wireshark removed'))
vulns.append(newCommandObject('apt list --installed | grep postgresql/', 'installed', False, 2, 'Prohibited software postgresql removed'))
vulns.append(newCommandObject('apt list --installed | grep apache2/', 'installed', False, 2, 'Prohibited software apache2 removed'))
vulns.append(newCommandObject('apt list --installed | grep armagetronad/', 'installed', False, 2, 'Prohibited software armagetronad removed'))
vulns.append(newCommandObject('apt list --installed | grep netris/', 'installed', False, 2, 'Prohibited software netris removed'))
vulns.append(newCommandObject('apt list --installed | grep nmap/', 'installed', False, 1, 'Prohibited software nmap removed'))
