vulns.append(newCommandObject('cat "/home/sackboy/Desktop/Forensics Question 1"', 'Play! Create! Share! Huzzah!', True, 8, 'Forensics question 1 solved'))
vulns.append(newCommandObject('cat "/home/sackboy/Desktop/Forensics Question 2"', '/etc/passwd', True, 8, 'Forensics question 2 solved'))
vulns.append(newCommandObject('cat "/home/sackboy/Desktop/Forensics Question 3"', '192.168.0.15', True, 8, 'Forensics question 3 solved'))
vulns.append(newUserObject('newton', False, None, None, 2, 'Removed hidden root newton'))
vulns.append(newUserObject('sackbot', False, None, None, 1, 'Removed unauthorized user sackbot'))
vulns.append(newUserObject('sackgirl', True, True, '!', 1, 'Set a password for sackgirl'))
vulns.append(newUserObject('negativatron', False, None, None, 2, 'Removed unauthorized hidden user negativatron'))
vulns.append(newCommandObject('sudo -l -U larrydavinci | grep "not allowed"', 'not allowed', True, 2, 'Larry Davinci is not an admin'))
vulns.append(newCommandObject('cat /etc/group | grep sudo | grep narrator', 'narrator', True, 1,  'Narrator is an admin'))
vulns.append(newCommandObject('cat /etc/sudoers | grep -c auth', '1', True, 1, 'Removed authentication bypass'))
vulns.append(newCommandObject('cat /etc/sudoers | grep -c auth', '0', True, 1, 'Removed authentication bypass'))
vulns.append(newCommandObject('cat /etc/sudoers.d/README | grep auth', "authenticate", False, 1, 'Removed authentication bypass'))
vulns.append(newCommandObject('ls /media/album | grep [.]mp3', 'mp3', False, 1, 'Removed unauthorized MP3 files'))
vulns.append(newCommandObject('ls /mnt/moon | grep passwords', 'passwords', False, 2, 'Removed plaintext passsword file'))
vulns.append(newCommandObject('cat /etc/samba/smb.conf | grep -i printers', 'printers', False, 2, 'Removed printers share'))
vulns.append(newCommandObject('cat /etc/samba/smb.conf | grep -i negativatron', 'negativatron', False, 1, 'Removed negativatron share'))
vulns.append(newCommandObject('cat /etc/crontab | grep "nc "', 'nc', False, 1, 'Removed backdoor in /etc/crontab'))
vulns.append(newCommandObject('cat /var/spool/cron/crontabs/root | grep "nc "', 'nc', False, 2, 'Removed backdoor in roots crontab'))
vulns.append(newCommandObject('ls -l /mnt | grep moon | grep drw-r-----', "drw-r-----", True, 2, 'Secure file permissions set for /mnt/moon'))
vulns.append(newCommandObject('ufw status', 'Status: active', True, 1, 'Firewall is enabled'))
vulns.append(newUserObject('root', True, True, '!', 1, 'Changed insecure root password'))
vulns.append(newConfigObject('/etc/login.defs', 'PASS_MAX_DAYS', '15', '\t', 2, 'A default maxiumum password age is set'))
vulns.append(newConfigObject('/etc/login.defs', 'PASS_MIN_DAYS', '7', '\t', 2, 'A default minimum password age is set'))
vulns.append(newCommandObject('ls /bin', 'ex1t', False, 5, 'Removed bad executable ex1t'))
vulns.append(newCommandObject('cat /etc/pam.d/common-password','minlen=', True, 2, 'A minimum length has been set for passwords'))
vulns.append(newCommandObject('cat /etc/rc.local', 'ex1t', False, 2, 'Removed startup backdoor'))
vulns.append(newCommandObject('ufw show added', 'deny 21', False, 4, 'Firewall allows port 21'))
vulns.append(newCommandObject('cat /etc/ssh/sshd_config | grep X11Forwarding', 'no', True, 2, 'Disabled X11 Forwarding'))
vulns.append(newCommandObject('cat /etc/ssh/sshd_config | grep PermitRootLogin', 'no', True, 2, 'Disabled root login via ssh'))
vulns.append(newCommandObject('cat /etc/ssh/sshd_config | grep Protocol', '2', True, 2, 'SSH Protocol set to 2'))
vulns.append(newCommandObject('ls /etc/cron.d', 'runcheck', False, 2, 'Removed backdoor in crontab'))
vulns.append(newCommandObject('ls -l /etc | grep -v gshadow | grep -v shadow- | grep shadow', '-rw-r-----', True, 2, 'Secure file permissions set for shadow file'))
vulns.append(newCommandObject('ls /var', 'timemachine', False, 3, 'Removed the timemachine'))
vulns.append(newCommandObject('cat /etc/samba/smb.conf | grep -A 8 "\[moon\]" | grep "guest ok"', 'no', True, 2, 'moon share does not allow guests'))
vulns.append(newCommandObject('cat /etc/samba/smb.conf | grep -A 8 "\[moon\]" | grep "create mask"', '0640', True, 2, 'moon share create mask hardened'))
vulns.append(newCommandObject('cat /etc/vsftpd.conf | grep -v "#"', 'anonymous_enable=NO', True, 1, 'VSFTPD no longer allows anonymous access'))
vulns.append(newCommandObject('cat /etc/vsftpd.conf | grep -v "#"', 'secure_chroot_dir=/var/chroot', True, 1, 'VSFTPD chroot is properly configured'))
vulns.append(newCommandObject('cat /etc/sysctl.conf | grep -v "#"', 'net.ipv4.icmp_echo_ignore_broadcasts = 1', True, 2, 'Ignore IPv4 ICMP echo broadcasts'))
vulns.append(newCommandObject('cat /etc/apt/apt.conf.d/20auto-upgrades | grep Update-Package-Lists', '"1"', True, 2, 'Automatically checks for updates'))
vulns.append(newCommandObject('apt list --installed | grep ophcrack/', 'installed', False, 2, 'Prohibited software ophcrack removed'))
vulns.append(newCommandObject('apt list --installed | grep wireshark/', 'installed', False, 2, 'Prohibited software wireshark removed'))
vulns.append(newCommandObject('apt list --installed | grep postgresql/', 'installed', False, 2, 'Prohibited software postgresql removed'))
vulns.append(newCommandObject('apt list --installed | grep apache2/', 'installed', False, 2, 'Prohibited software apache2 removed'))
vulns.append(newCommandObject('apt list --installed | grep armagetronad/', 'installed', False, 2, 'Prohibited software armagetronad removed'))
vulns.append(newCommandObject('apt list --installed | grep netris/', 'installed', False, 2, 'Prohibited software netris removed'))
vulns.append(newCommandObject('apt list --installed | grep nmap/', 'installed', False, 1, 'Prohibited software nmap removed'))
vulns.append(newCommandObject('cat /home/tanjiro/Desktop/forensics1.txt', 'zenitsu', True, 4, 'Forensics Question 1 correct'))
vulns.append(newCommandObject('cat /home/tanjiro/Desktop/forensics2.txt', '1234', True, 4, 'Forensics Question 2 correct'))
vulns.append(newCommandObject('cat /home/tanjiro/Desktop/forensics3.txt', 'IMACTUALLYMICHAELJACKSON', True, 4, 'Forensics Question 3 correct'))
vulns.append(newCommandObject('cat /etc/passwd', 'dns', False, 1, 'Removed unauthorized user'))
vulns.append(newCommandObject('cat /etc/passwd', 'rui', False, 1, 'Removed unauthorized user'))
vulns.append(newCommandObject('cat /etc/passwd', 'muzan', False, 1, 'Removed unauthorized user'))
vulns.append(newCommandObject('cat /etc/passwd', 'debiansys', False, 1, 'Removed unauthorized user'))
vulns.append(newCommandObject('cat /etc/passwd', 'critlampuser', False, 1, 'Removed unauthorized user'))
vulns.append(newCommandObject('cat /etc/shadow | grep zenitsu', '18273', False, 1, 'Changed zenitsu\'s password'))
vulns.append(newCommandObject('cat /etc/shadow | grep nezuko', '18273', False, 1, 'Changed nezuko\'s password'))
vulns.append(newCommandObject('cat /etc/group | grep 27', 'crow', True, 1, 'Added crow as admin'))
vulns.append(newCommandObject("cat /etc/group | grep 27 | grep -Eo \'(urokodaki|tamayo|tomioka|shinobu)\' | wc -l", '4', True, 2, 'urokodaki, tamayo, tomioka, and shinobu are all admins'))
vulns.append(newCommandObject("ufw status | grep -E \'(21|22|80|3306)\' | grep ALLOW | wc -l", '4', True, 2, 'Firewall allows FTP, SSH, and LAMP stack'))
vulns.append(newCommandObject("stat -c '%a' /etc/passwd", '644', True, 2, 'System hardening check passed'))
vulns.append(newCommandObject('cat /etc/pam.d/common-password | grep pam_cracklib.so', 'gecoscheck', True, 1, 'System hardening check passed'))
vulns.append(newCommandObject('cat /etc/pam.d/common-password | grep pam_unix.so', 'sha512', True, 1, 'System hardening check passed'))
vulns.append(newCommandObject('stat -c %a /etc/grub.d ', '777', False, 3, 'System hardening check passed'))
vulns.append(newCommandObject('cat /etc/host.conf | grep nospoof', 'on', True, 2, 'System hardening check passed'))
vulns.append(newCommandObject('ls -la /etc/skel', '.sysclean', False, 4, 'Removed backdoor'))
vulns.append(newCommandObject('cat /etc/login.defs | grep -E \'(PASS_MAX_DAYS|PASS_MIN_DAYS)\' | grep -v "#" | grep -E \'(99999|0)\' | wc -l', '0', True, 2, 'A default min/max password age set'))
vulns.append(newCommandObject('cat /etc/gdm3/greeter.dconf-defaults | grep disable-user-list', 'true', True, 3, 'System hardening check passed'))
vulns.append(newCommandObject('cat /etc/sysctl.conf | grep net.ipv4.tcp_syncookies', '1', True, 2, 'Sysctl hardening check passed'))
vulns.append(newCommandObject('cat /etc/sysctl.conf | grep net.ipv4.ip_forward', '0', True, 2, 'Sysctl hardening check passed'))
vulns.append(newCommandObject('cat /etc/sysctl.conf | grep net.ipv6.conf.all.disable_ipv6', '0', True, 2, 'Sysctl hardening check passed'))
vulns.append(newCommandObject('apt list --installed p0f', 'installed', False, 1, 'Unauthorized software removed'))
vulns.append(newCommandObject('apt list --installed openarena', 'installed', False, 1, 'Unauthorized software removed'))
vulns.append(newCommandObject('apt list --installed kismet', 'installed', False, 1, 'Unauthorized software removed'))
vulns.append(newCommandObject('apt list --installed tightvncserver', 'installed', False, 1, 'Unauthorized software removed'))
vulns.append(newCommandObject('apt list --installed medusa', 'installed', False, 1, 'Unauthorized software removed'))
vulns.append(newCommandObject('apt list --installed john', 'installed', False, 1, 'Unauthorized software removed'))
vulns.append(newCommandObject('cat /etc/fstab', 'noexec', True, 3, 'Stricter defaults have been enabled for shared memory'))
vulns.append(newCommandObject('ls -l /bin/nano', 'rwsrwxrwx', False, 5, 'nano is no longer SUID'))
vulns.append(newCommandObject('apt list --installed apache2 vsftpd mysql-server openssh-server php7.0 | wc -l', '6', True, 1, 'FTP, SSH, and LAMP are installed'))
vulns.append(newCommandObject('cat /etc/vsftpd.conf | grep anonymous_enable', 'NO', True, 2, 'Application security check'))
vulns.append(newCommandObject('cat /etc/vsftpd.conf | grep secure_chroot_dir', '/srv/ftp', True, 2, 'Application security check passed'))
vulns.append(newCommandObject('cat /etc/apache2/apache2.conf | grep ServerSignature', 'Off', True, 2, 'Software security check passed'))

vulns.append(newCommandObject('cat /etc/apache2/apache2.conf | grep ServerTokens', 'Prod', True, 2, 'Software security check passed'))

vulns.append(newCommandObject('cat /etc/mysql/my.cnf | grep bind-address', '127.0.0.1', True, 2, 'Software security check passed'))

vulns.append(newCommandObject('cat /etc/php/7.0/apache2/php.ini | grep expose_php', 'Off', True, 2, 'Software security check passed'))
vulns.append(newCommandObject('cat /etc/ssh/sshd_config | grep PermitRootLogin', 'no', True, 2, 'Software security check passed'))
vulns.append(newCommandObject('cat /etc/login.defs | grep -E \'(UID_MIN|SYS_UID)\' | grep -Ew \'(1000|100|999)\' | wc -l', '3', True, 3, 'Corrected incorrect system setting'))
vulns.append(newCommandObject('ls /bin', 'nologin', False, 4, 'Removed /bin/nologin'))
vulns.append(newCommandObject('cat /etc/adduser.conf | grep DSHELL', '/bin/bash', True, 3, 'Default shell changed to /bin/bash'))
vulns.append(newCommandObject('cat /etc/passwd | grep -E \'^(daemon|games|man)\' | grep nologin', 'nologin', False, 3, 'Changed shell for daemon, games, man from /bin/nologin'))
vulns.append(newCommandObject('ls -R /home | grep "rf"', 'rf', False, 4, 'Removed tricky directory ahahaahaa'))
